### ISSUE TITLE
Allow users to Ignore Filter Suggestions for loaded dimensions

### ISSUE THREAD

**Issue by colemanProjects** [yavin-dev/framework#1041]
**Is your feature request related to a problem? Please describe.**
Users are frustrated when they can't find a value to filter on, and the UI doesn't let them attempt to filter on it

**Describe the solution you'd like**
Allow users to simply type whatever they want and press enter. That value should be added to the list. (should be careful not to confuse the ergonomics of select something from the dropdown, we don't want a conflict between selecting a value and entering what you type

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jkusa** [comment]
closed via #1519
