### ISSUE TITLE
Metric parsing error (alpha branch)

### ISSUE THREAD

**Issue by cythrawll** [yavin-dev/framework#1142]
**Describe the bug**
parsing a metric with empty () fails in `parseMetricName` in `navi-data/utils/metric.js`

**To Reproduce**
1. Load a report that has a metric such as "metricName()" 

**Expected behavior**
Should handle it equivalent to "metricName"

**Screenshots**

**Additional context**

**Comment by jkusa** [comment]
@cythrawll is this still valid? Also, since this is on alpha, do you feel we still need to track it?
