### ISSUE TITLE
Reference CID in sorts

### ISSUE THREAD

**Issue by cythrawll** [yavin-dev/framework#1565]
**Describe the bug**
Saving a sort in request v2, we don't save the reference CID that points to the column. So if that column changes we can't change the corresponding sort. Giving us the only option is to remove all sorts that match the base metric.

**Expected behavior**
When we change a parameter on the metric, the sort should update that parameter as well

**Comment by kevinhinterlong** [comment]
Resolved by https://github.com/yavin-dev/framework/pull/1585
