### ISSUE TITLE
line chart Series don't refresh upon opening a report

### ISSUE THREAD

**Issue by colemanProjects** [yavin-dev/framework#289]
Had a saved report with a default visualization as a line chart. 
The line chart had all flat lines when i opened the report but when I navigate to the table and back to the line chart (without making any changes to the report) the line chart looked pretty different. 

My suspicion is that we don't call `rebuildConfig` upon loading a report, and thus when we load it, the previously saved series are loaded. But, when we click on the visualization toggle, we call `rebuildConfig and the line chart contains new series.

**Comment by cythrawll** [comment]
Was there visualization settings that got wiped when you switched viz?
