### ISSUE TITLE
Remove navi-report__action-link--force-disabled class

### ISSUE THREAD

**Issue by daniellevinson** [yavin-dev/framework#442]
**Is your feature request related to a problem? Please describe.**
In a few places we're forcing a disabled element by adding the class
```
.navi-report__action-link--force-disabled {
  color: @disabled-gray !important;
  cursor: not-allowed !important;
}
```
Probably because some child's `cursor` and `color` styles ignore its parent's disabled attribute/class.

**Describe the solution you'd like**
Avoid forcing styles with `!important` in those cases.

**Comment by adhyapranata** [comment]
Hi @daniellevinson, to clarify, do you want to remove the class or just remove the `!important` to resolve this issue? I would like to help

**Comment by mattgraham1995** [comment]
@adhyapranata We're looking to apply these styles still, but we would like to do so by using a more specific selector rather than forcing the styles using the `!important` tag.

**Comment by jkusa** [comment]
https://github.com/yavin-dev/framework/blob/13bc1a151bef5113b3a7248404822915fba0b44f/packages/reports/addon/templates/components/navi-action-list.hbs#L8
