### ISSUE TITLE
Desc Field for dimensions

### ISSUE THREAD

**Issue by balajimanoharan** [yavin-dev/framework#541]
**Is your feature request related to a problem? Please describe.**
We have an api that generates a different display field, but navi relies heavily on a field called `desc` to be used as the display field

**Describe the solution you'd like**
Make the display field configurable

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by cythrawll** [comment]
We have this somewhat covered with field tags in meta-data.  Though I'm not sure how well it's supported everywhere.

**Comment by jkusa** [comment]
done in request v2
