### ISSUE TITLE
Hourly Timegrain reporting has inconsistent boundaries

### ISSUE THREAD

**Issue by colemanProjects** [yavin-dev/framework#620]
**Describe the bug**
2 issues. 
- If I ask for 2 days, split by hour, i get 24 rows back (I expect 48).  
- If i ask for any hourly timegrain, the table shows a different end time than the line chart

**To Reproduce**
1. Build a report and select hourly timegrain
2. Click on the table and find the end time
3. Compare that to the end time after clicking on the calendar

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jkusa** [comment]
Closing in favor of #1298
