### ISSUE TITLE
Remove Redundant Table Components

### ISSUE THREAD

**Issue by mattgraham1995** [yavin-dev/framework#628]
**Is your feature request related to a problem? Please describe.**
We have navi-collection and dir-table that currently serve very similar purposes. 

**Describe the solution you'd like**
These should be condensed to a common component that can be used in place of either.

**Describe alternatives you've considered**
We could possibly remove the directory package and have its contents owned by navi-core. That way directory would be the index route for any collection.

**Comment by jkusa** [comment]
Closing in favor of #617 1299
