### ISSUE TITLE
Collapsed View of Filter Selector Misaligned

### ISSUE THREAD

**Issue by colemanProjects** [yavin-dev/framework#703]
**Describe the bug**
<img width="664" alt="Screen Shot 2020-03-05 at 2 45 41 PM" src="https://user-images.githubusercontent.com/3818860/76024090-1d99c480-5ef0-11ea-91cb-d7a98f006bc7.png">

**To Reproduce**
1. Go to 'the report view'
2. Collapse the filter builder
3. Look at the top left
4. The sections are misaligned

**Expected behavior**
An alignment between the table selector and the filter selector

**Screenshots**
Screenshot above.

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Additional context**
N/A

**Comment by mattgraham1995** [comment]
@ashishag24
