### ISSUE TITLE
Change main branch from "master"

### ISSUE THREAD

**Issue by cythrawll** [yavin-dev/framework#857]
We should change our main branch from "master" probably to "main" going to look into seeing if our OSS coordinator is going to come up with a standard.

**Comment by mattgraham1995** [comment]
I vote for `trunk` like the trunk of a tree

**Comment by cythrawll** [comment]
@mattgraham1995 that's takes me back to SVN

**Comment by mattgraham1995** [comment]
Sounds like there's established precedence then 🤔
