### ISSUE TITLE
Grouped-List Enhancements

### ISSUE THREAD

**Issue by mattgraham1995** [yavin-dev/framework#908]
**Is your feature request related to a problem? Please describe.**
Currently, if grouped-list loads a list of items where the groupByField value is the same for every single item, we get a long list that's needlessly nested under a header of that groupByField value. Also, items in the list with a falsy value end up in a group called 'Uncategorized'. This only makes sense if the groupByField is `category`. 

**Describe the solution you'd like**
- Remove the grouping if there is only a single group
- Since grouped-list isn't used outside of the one use-case in navi-reports, we should just make it always group on `category`.

**Comment by jkusa** [comment]
> Remove the grouping if there is only a single group

Closed via #1510


> Since grouped-list isn't used outside of the one use-case in navi-reports, we should just make it always group on category.

Closing for now
